import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { runImportBatch } from "@/lib/import/run-batch";
import type { ImportRow } from "@/lib/import/types";

/**
 * QR Student Import: scans a QR code that encodes a JSON payload of one
 * student's basic info (e.g. generated by another school's export) and
 * feeds it through the same single-row creation pipeline as every other
 * import source. Reuses Module 3's QR-scanning UI pattern client-side
 * (manual code entry / camera decode both land here as plain text) — this
 * route only needs the already-decoded JSON string.
 *
 * Body: { payload: string } where payload is a JSON-encoded ImportRow-ish object.
 */
export async function POST(request: NextRequest) {
  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getUser();
  if (!auth?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: profile } = await supabase.from("users").select("school_id").eq("id", auth.user.id).single();
  if (!profile?.school_id) {
    return NextResponse.json({ error: "No school associated with this user" }, { status: 400 });
  }

  const body = await request.json().catch(() => null);
  if (!body?.payload) {
    return NextResponse.json({ error: "Missing payload" }, { status: 400 });
  }

  let parsed: Partial<ImportRow>;
  try {
    parsed = JSON.parse(body.payload);
  } catch {
    return NextResponse.json({ error: "QR payload ไม่ใช่ JSON ที่ถูกต้อง" }, { status: 400 });
  }

  const row: ImportRow = {
    rowNumber: 1,
    student_code: parsed.student_code ?? "",
    full_name: parsed.full_name ?? "",
    nickname: parsed.nickname,
    gender: parsed.gender,
    birth_date: parsed.birth_date,
    citizen_id: parsed.citizen_id,
    phone_number: parsed.phone_number,
    grade: parsed.grade,
    classroom: parsed.classroom,
    risk_level: parsed.risk_level,
    parent_full_name: parsed.parent_full_name,
    parent_relationship: parsed.parent_relationship,
    parent_phone: parsed.parent_phone,
    parent_line_id: parsed.parent_line_id,
    height_cm: parsed.height_cm,
    weight_kg: parsed.weight_kg,
    allergies: parsed.allergies,
    chronic_conditions: parsed.chronic_conditions,
    raw: {},
  };

  try {
    const result = await runImportBatch({
      supabase,
      schoolId: profile.school_id,
      importedBy: auth.user.id,
      source: "qr",
      fileName: null,
      rows: [row],
      defaultStrategy: "skip",
    });
    return NextResponse.json(result, { status: 200 });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Import failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
